AllCops:
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'
    - '*.gemspec'
    - 'Rakefile'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/ExtraSpacing:
  Enabled: true

SpaceAroundOperators:
  Enabled: false

Documentation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  CountComments: false
  Max: 150

Metrics/ModuleLength:
  CountComments: false
  Max: 150

Metrics/MethodLength:
  CountComments: false
  Max: 15
