AllCops:
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'
    - '*.gemspec'
    - 'Rakefile'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/ExtraSpacing:
  Enabled: true

SpaceAroundOperators:
  Enabled: false

Documentation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 15

Metrics/ClassLength:
  CountComments: false
  Max: 150

Metrics/MethodLength:
  CountComments: false
  Max: 10
