AllCops:
  Exclude:
    - 'spec/*'
    - 'Guardfile'
    - '*.gemspec'
    - 'Rakefile'

Documentation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
