version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle
      - run: bundle exec rspec

workflows:
  tests:
    jobs:
      - test

