version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  test_ruby_2_7:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle
      - run: bundle exec rspec
  test_ruby_2_6:
    docker:
      - image: cimg/ruby:2.6
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle
      - run: bundle exec rspec

workflows:
  tests:
    jobs:
      - test_ruby_2_7
      - test_ruby_2_6

